# Generated by Django 3.0.8 on 2021-06-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('desc', models.TextField(max_length=120)),
                ('location', models.CharField(max_length=20)),
                ('pay_range', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('#1', 'None'), ('#2', 'Active'), ('#3', 'Closed')], default='#1', max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
