# Generated by Django 3.0.8 on 2021-06-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=36, null=True)),
                ('city', models.CharField(blank=True, max_length=18, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume')),
                ('graduation_year', models.IntegerField(blank=True)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], default='Full Time', max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='desc',
            field=models.TextField(max_length=320),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay_range',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Active', 'Active'), ('Closed', 'Closed')], default='None', max_length=6),
        ),
    ]
